config_version = 13

[accessibility]
ui_scale = 1.1000000089406967

[bar]
order = [ "default" ]

    [bar.default]
    center = [ "workspaces" ]
    concave_edge_corners = false
    end = [ "group:g1", "battery", "clock" ]
    margin_edge = 5
    margin_ends = 4
    padding = 10
    position = "left"
    scale = 0.95000000670552254
    start = [ "control-center", "network", "bluetooth", "cat" ]
    thickness = 30
    widget_spacing = 14

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "sysmon", "cpu", "ram" ]
        opacity = 1.0
        padding = 6.0

[location]
address = "Rotterdam, NL"

[lockscreen]
enabled = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 1280.0
    cy = 1321.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/kaomoji", "noctalia/mpvpaper", "oldirtty/color_picker", "noctalia/bongocat" ]

[shell]
corner_radius_scale = 1.3000000193715096
font_family = "DejaVu Sans"
lang = "en"

    [shell.launcher]
    categories = false
    fetch_exchange_rates = false
    show_app_actions = true
    show_app_origin_indicator = false

    [shell.panel]
    launcher_placement = "floating"
    open_near_click_control_center = true
    open_near_click_session = true
    transparency_mode = "soft"

    [shell.screen_corners]
    enabled = true
    size = 13

[theme]
builtin = "Nord"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "hyprland", "qt" ]

[wallpaper]
enabled = false

    [wallpaper.default]
    path = "/nix/store/9d9xp7d8xrdmv8ywhbakm7b71x3wv02i-noctalia-5.0.0/share/noctalia/assets/noctalia-wallpaper.png"

    [wallpaper.last]
    path = "/nix/store/9d9xp7d8xrdmv8ywhbakm7b71x3wv02i-noctalia-5.0.0/share/noctalia/assets/noctalia-wallpaper.png"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.cat_2]
type = "noctalia/bongocat:cat"

[widget.clock]
vertical_format = "{:%H\\n%M}"

[widget.cpu]
show_value = false
stat = "cpu_temp"

[widget.launcher]
enabled = false

[widget.network]
show_label = false

[widget.ram]
show_value = false

[widget.sysmon]
show_value = false

[widget.workspaces]
show_labels = false